### ISSUE TITLE
Readme outdated.

### ISSUE THREAD

**Issue by el-hult** [allentran/pca-magic#10]
The API for the PPCA class changed in this commit: https://github.com/allentran/pca-magic/commit/e3277fbb62f741e019c2f213a9bc3401edbaf64b#diff-55e08643559cb5b322fec1eb066e0c77R9 

On the other hand, the readme doesnt reflect this. Latest update says you should pass data into the constructor: https://github.com/allentran/pca-magic/commit/b056214fd9f56049ab11af4fed2f604258e234af#diff-04c6e90faac2675aa89e2176d2eec7d8R17

It would get much easier to use your library (which is super helpful!) if the readme was correct. Please consider updating!

**Comment by allentran** [comment]
Thanks/updated, appreciate the help.
