### ISSUE TITLE
The dimention of component is always 2

### ISSUE THREAD

**Issue by ghost** [allentran/pca-magic#2]
Hi Allen, first of thanks for your great work. I have tried your code but seems that the resulting `component_mat` always has the shape of `(#data, 2)` no matter what the value `d` have. Could you please take a look and see what is the reason? Thanks in advance!

**Comment by allentran** [comment]
You need to supply the parameter `d` to fit.  E.g to use 4 components

```
pca = PPCA()
pca.fit(data, d=4)
```
