### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by andrewheusser** [allentran/pca-magic#3]
Hi Allen,

We are hoping to use your PPCA implementation for a [toolbox](http://hypertools.readthedocs.io/en/latest/) to visualize high dimensional data.  I'd like to submit a small PR to add python3 support, but wanted to clarify something first. In the middle of the implementation, you import IPython, is that on purpose, or some debugging code left in on accident? Thanks!

https://github.com/allentran/pca-magic/blob/master/ppca/_ppca.py#L110

Andy

**Comment by allentran** [comment]
Apologies for the late response, that `IPython` import was leftover debug code for sure, it's removed now.
